### ISSUE TITLE
[Feature Request] Support TLS on published metrics endpoint

### ISSUE THREAD

**Issue by bartkleypas** [veertuinc/anka-prometheus-exporter#47]
Communication via TLS is supported to/from the Anka controller, but this does not seem to be the case for the metrics being published in turn by this exporter.

**Comment by NorseGaud** [comment]
Blocked by https://github.com/prometheus/exporter-toolkit/issues/254. Seems like their toolkit outputs logs not as JSON in specific situations. We can't have that :(

**Comment by NorseGaud** [comment]
RC1 ready for testing: https://github.com/veertuinc/anka-prometheus-exporter/releases/tag/v4.0.0-rc1
