### ISSUE TITLE
CLOUD-747: v2.0: Registry Disk Used Incorrect Label or Data

### ISSUE THREAD

**Issue by daniel-chapa-nike** [veertuinc/anka-prometheus-exporter#5]
The `anka_registry_disk_used_space` label is returning data that was previously labeled as `anka_registry_total_space_gb`. Unsure if this metric is mislabeled or providing incorrect data.

Expected Results:
- Value for `anka_registry_disk_used_space`

Observed Results:
- Value representing `anka_registry_total_space`

![Screen Shot 2021-02-24 at 10 46 10 AM](https://user-images.githubusercontent.com/79281454/109051185-1f274400-768f-11eb-9139-dac1c240ab3d.png)

**Comment by NorseGaud** [comment]
https://github.com/veertuinc/anka-prometheus-exporter/releases/tag/v2.1.0
